### ISSUE TITLE
Question Deep Learning

### ISSUE THREAD

**Issue by nguymi01** [ulfaslak/artificial_neural_networks_and_deep_learning#2]
For CNN in Keras, shouldn't it be MaxPooling2D instead of MaxPool2D?

**Comment by ulfaslak** [comment]
Correct. You're welcome to make the pull request and get an extra credit point!

**Comment by nguymi01** [comment]
Can't I just get the credit, I don't know how to pull request lol

**Comment by ulfaslak** [comment]
Google it. You probably have to learn it eventually anyway :).

**Comment by ulfaslak** [comment]
Well done!
