### ISSUE TITLE
Assignment 1 Ex 1.2.3

### ISSUE THREAD

**Issue by nguymi01** [ulfaslak/artificial_neural_networks_and_deep_learning#6]
For Ex 1.2.3, did you want us to use the same size as Ex 1.2.2 and commented on the sizes, or you wanted us to make a whole new model than Ex 1.2.2 ?

**Comment by ulfaslak** [comment]
**1**.2.3? Sure you mean **1**? If so, I can't make sense of this question, I'm afraid.

**Comment by nguymi01** [comment]
Now we want to do the same thing as in Ex. 1.2.2, but with the data generated with the generate_X_nonlinear function. Comment on the result! 

So you wanted us to keep everything from Ex 1.2.2 and just changed the data from linear to non-linear right?

**Comment by ulfaslak** [comment]
Wait sorry, I was looking in the wrong course... Here's the answer:

I understand the confusion. In 1.2.2 I specify what sizes to use, but I don't in 1.2.3.

> So you wanted us to keep everything from Ex 1.2.2 and just changed the data from linear to non-linear right?

No in 1.2.3, you should of course use a different model than in 1.2.2, since sizes [2, 1] would not work for the non-linear problem.
